### ISSUE TITLE
Digger CLI - invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by chvima** [diggerhq/digger#1112]
I have issue in the workflow of digger apply (I have another issues described in https://github.com/diggerhq/digger/issues/1110 , but this one is when I don't use upload-plan-destination: github)
Everything runs correctly, apply succeeds, Github Application creates the comment, but the pipeline crashes in the end because of error in digger.go:

```
Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

no $DIGGER_OUT file at: /__w/_temp/digger-out.log
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1465278]

goroutine 1 [running]:
github.com/diggerhq/digger/cli/pkg/digger.RunJobs({0xc001197ae0, 0x1, 0xc000c1c630?}, {0x24d1f80, 0xc000be6db0}, {0x24b2be0, 0xc000be6db0}, {0x24c51f0, 0xc000126440}, {0x24be0a8, ...}, ...)
	/home/runner/work/digger/digger/cli/pkg/digger/digger.go:137 +0x3b8
main.gitHubCI({0x24c51f0, 0xc000126440}, {0x24c4f20, 0xc000acf9b0}, {0x24c4f50, 0xc000bc6360}, {0x24b2b20?, 0xc000ae25d0})
	/home/runner/work/digger/digger/cli/cmd/digger/main.go:158 +0x1247
main.main()
	/home/runner/work/digger/digger/cli/cmd/digger/main.go:852 +0xa5c
Error: Error: failed to run script step: command terminated with non-zero exit code: error executing command [sh -e /__w/_temp/614250b0-c104-11ee-93dc-e7b51bfeb18a.sh], exit code 2
Error: Process completed with exit code 1.
Error: Executing the custom container implementation failed. Please contact your self hosted runner administrator.
```

To compare, successfull log from plan:
```
Plan: 1 to add, 0 to change, 0 to destroy.
─────────────────────────────────────────────────────────────────────────────
Saved the plan to:
/__w/XXX/XXX/YYY.tfplan

To perform exactly these actions, run the following command to apply:
 ...
Running command: terraform [show -no-color -json ...]
no $DIGGER_OUT file at: /__w/_temp/digger-out.log
No plan policies found, succeeding
Digger finished successfully
Run if [[ "workflow_dispatch" == "issue_comment" ]]; then
Run '/home/runner/k8s/index.js'
```

Using self hosted backend v3.19.0, action of the same version. I don’t know how to replicate the issue. Ideally, the cli would have more info and debug logs to identify the cause, I can try to add those and build my own version.

**Comment by chvima** [comment]
Tried the following, still the same issue:
- v3.20.0
- github hosted runners (ubuntu-latest) instead of my custom runners
- debug mode (there was no more logs)
- disable merge on apply

**Comment by noralutz** [comment]
Also seeing a similar issue; no plan/applies work with action + backend versions 0.3.17+ using the GithubCI. 

```
18:34:15 locking.go:248: Using NoOp lock provider.
18:34:15 root.go:113: Lock provider has been created successfully
18:34:15 main.go:39: Using GitHub.
18:34:15 main.go:76: GitHub context parsed successfully
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x70 pc=0x193e813]

goroutine 1 [running]:
main.gitHubCI({0x2597658, 0x364bf00}, {0x2596c98, 0xc0009bfbb0}, {0x2596cc8, 0xc000b464e0}, {0x25842c0?, 0xc000625de8})
	/home/runner/work/_actions/diggerhq/digger/latest/cli/cmd/digger/main.go:128 +0xc93
main.glob..func2(0xc000b4e200?, {0x1f565b4?, 0x4?, 0x1f565b8?})
	/home/runner/work/_actions/diggerhq/digger/latest/cli/cmd/digger/default.go:23 +0x205
github.com/spf13/cobra.(*Command).execute(0x35e3c40, {0x364bf00, 0x0, 0x0})
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:987 +0xaa3
github.com/spf13/cobra.(*Command).ExecuteC(0x35e44e0)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1115 +0x3ff
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1039
main.main()
	/home/runner/work/_actions/diggerhq/digger/latest/cli/cmd/digger/main.go:815 +0xf4
Error: Process completed with exit code 2.
```

**Comment by motatoes** [comment]
thanks for documenting @chvima let me have a look it might be a regression from our most recent changes to go multici

**Comment by motatoes** [comment]
I have reproduced @chvima 's issue, @noralutz I believe has a different issue which I am debugging with her on slack, seems to be stemming from an error during reporting status to backend which was uncaught

**Comment by chvima** [comment]
Thanks for quick fix! Looking forward for next release 👍

**Comment by chvima** [comment]
I've tested and confirm the issue was resolved.
