### ISSUE TITLE
panic: runtime error: slice bounds out of range

### ISSUE THREAD

**Issue by frank-bee** [diggerhq/digger#285]
I get the following error.
Unfortunately there is no clear error message and in the go code I don't find the origin of the error ( without further debugging )

```
Saved the plan to: terraform-platform#dev.tfplan

To perform exactly these actions, run the following command to apply:
    terraform apply "terraform-platform#dev.tfplan"
panic: runtime error: slice bounds out of range [200628:200426]

goroutine 1 [running]:
digger/pkg/digger.cleanupTerraformOutput(0x1, {0x0, 0x0?}, {0xc0006f0000, 0x325fb}, {0x0, 0x0}, 0xc0005b11c8)
	/home/runner/work/digger/digger/pkg/digger/digger.go:598 +0x1d4
digger/pkg/digger.cleanupTerraformPlan(...)
	/home/runner/work/digger/digger/pkg/digger/digger.go:607
digger/pkg/digger.DiggerExecutor.Plan({{0xc000648240, 0x13}, {0xc000648254, 0x12}, {0xc0007f812c, 0x3}, {0xc0007f8518, 0x3}, 0xc0003da150, 0xc0003da180, ...}, ...)
	/home/runner/work/digger/digger/pkg/digger/digger.go:456 +0x71c
digger/pkg/digger.RunCommandsPerProject({0xc000588000, 0x1, 0x9?}, {0xc000648240, 0x13}, {0xc000648254, 0x12}, {0xc0007cc590, 0xc}, 0x261, ...)
	/home/runner/work/digger/digger/pkg/digger/digger.go:106 +0x7e5
main.gitHubCI({0x128ea6d?, 0xc00003e2f8?})
	/home/runner/work/digger/digger/cmd/digger/main.go:85 +0x845
main.main()
	/home/runner/work/digger/digger/cmd/digger/main.go:207 +0x23c
Error: Process completed with exit code 2.
```

**Comment by motatoes** [comment]
Hi @frank-bee this issue is fixed in #284 , currently being reviewd

**Comment by frank-bee** [comment]
cool, thanks for the quick reply :-)

**Comment by frank-bee** [comment]
this issue is gone now !

but I cannot do a "digger plan" or "digger apply" via PR comment

this is the output 

```
...
2023/05/24 07:42:37 Successfully connected to AWS account ***, user Id: AROAWP7DAB6HJUFVI7RCZ:GitHubActions
Lock provider has been created successfully
2023/05/24 07:42:37 Following projects are impacted by pull request #622
GitHub event processed successfully
GitHub event converted to commands successfully
2023/05/24 07:42:37 Following commands are going to be executed:
Commands executed successfully
Digger finished successfully.
```

**Comment by frank-bee** [comment]
@motatoes 
but the plan is running if I just commit to the PR branch 

```
...
Digger config read successfully
2023/05/24 07:49:03 Using AWS lock provider.
2023/05/24 07:49:03 Successfully connected to AWS account ***, user Id: AROAWP7DAB6HJUFVI7RCZ:GitHubActions
Lock provider has been created successfully
2023/05/24 07:49:04 Following projects are impacted by pull request #622
dev
GitHub event processed successfully
GitHub event converted to commands successfully
2023/05/24 07:49:04 Following commands are going to be executed:
project: dev: commands: "digger plan", 
```

**Comment by frank-bee** [comment]
somehow now I can do a plan...
but I get this error

![image](https://github.com/diggerhq/digger/assets/275327/175ec40d-a31d-4a3b-9695-a6d1b6452428)

**Comment by frank-bee** [comment]
duplicate
